version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_news
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: newsdb
    ports:
      - "5432:5432"